#!/bin/bash  -l 
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1 
#SBATCH --mem-per-cpu=4G
#SBATCH --partition=devel
#SBATCH --time=00:10:00 
#SBATCH --job-name=subdevel

module load LAMMPS/29Aug2024_update2-foss-2023a-kokkos
mpirun lmp -in lipf6.in > lipf6.out
