#!/bin/bash  -l 
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=48 
#SBATCH --mem-per-cpu=4G
#SBATCH --partition=short
#SBATCH --time=04:00:00 
#SBATCH --job-name=subshort

module load LAMMPS/29Aug2024_update2-foss-2023a-kokkos
mpirun lmp -in lipf6.in4LL > lipf6.out
